#!/usr/bin/env python3
"""
linacre.py — Unified CLI for the linacre.site project.

Replaces: setup-env.bat, setup_env.py, sync_vercel.py, linacre-launcher.ps1

Usage:
    python linacre.py setup      Scan Windows Registry → write .env
    python linacre.py sync       Push secrets to Vercel
    python linacre.py dev        Install deps if needed → sync env → start dev server
    python linacre.py build      Sync env → production build
    python linacre.py boot       Zero-click PC boot sequence (bg server + agent + browser)
    python linacre.py open       Open linacre.site in default browser
    python linacre.py status     Show project health: Node, keys, Vercel login
    python linacre.py verify     Verify Registry, .env, and Vercel are in sync
    python linacre.py audit      Scan for hardcoded secrets in config files
    python linacre.py help       Show this help
"""

import os
import sys
import json
import subprocess
import shutil
import webbrowser
import time
from pathlib import Path

# ─── Constants ───────────────────────────────────────────────────────────────
PROJECT_DIR = Path(__file__).parent.resolve()
ENV_PATH = PROJECT_DIR / ".env"
KEYS_TO_SYNC = [
    "GEMINI_API_KEY",
    "OPENAI_API_KEY",
    "ANTHROPIC_API_KEY",
    "CLAUDE_API_KEY",
    "LITELLM_API_KEY",
    "DASHBOARD_PASSWORD_HASH",
    "DASHBOARD_SESSION_SECRET",
    "GITHUB_TOKEN",
    "GOOGLE_API_KEY",
    "GOOGLE_CLIENT_ID",
    "GOOGLE_CLIENT_SECRET",
    "HUGGINGFACE_TOKEN",
    "OPENROUTER_API_KEY",
    "OPENCLAW_GATEWAY_TOKEN",
    "OPENAI_WHISPER_API_KEY",
]

AMBER = "\033[38;2;245;158;11m"
GREEN = "\033[38;2;52;211;153m"
RED   = "\033[38;2;251;113;133m"
DIM   = "\033[2m"
BOLD  = "\033[1m"
RESET = "\033[0m"


# ─── Utilities ───────────────────────────────────────────────────────────────

def _set_encoding():
    """Force UTF-8 output on Windows."""
    if hasattr(sys.stdout, "reconfigure"):
        try:
            sys.stdout.reconfigure(encoding="utf-8")
        except Exception:
            pass


def _banner(text: str):
    print(f"\n{AMBER}{BOLD}{'─' * 52}{RESET}")
    print(f"{AMBER}{BOLD}  {text}{RESET}")
    print(f"{AMBER}{BOLD}{'─' * 52}{RESET}\n")


def _ok(msg: str):
    print(f"  {GREEN}✓{RESET} {msg}")


def _warn(msg: str):
    print(f"  {RED}⚠{RESET} {msg}")


def _info(msg: str):
    print(f"  {DIM}→{RESET} {msg}")


def _get_windows_env(name: str) -> str | None:
    """Read a variable from Windows Registry, falling back to process env."""
    if sys.platform != "win32":
        return os.environ.get(name)
    import winreg
    # User env
    try:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, "Environment") as key:
            value, _ = winreg.QueryValueEx(key, name)
            return value
    except FileNotFoundError:
        pass
    # System env
    try:
        with winreg.OpenKey(
            winreg.HKEY_LOCAL_MACHINE,
            r"SYSTEM\CurrentControlSet\Control\Session Manager\Environment",
        ) as key:
            value, _ = winreg.QueryValueEx(key, name)
            return value
    except FileNotFoundError:
        pass
    return os.environ.get(name)


def _read_env() -> dict[str, str]:
    """Parse the existing .env file into a dict."""
    env_vars: dict[str, str] = {}
    if ENV_PATH.exists():
        for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                env_vars[k.strip()] = v.strip()
    return env_vars


def _write_env(env_vars: dict[str, str]):
    """Write dict back to .env with header comment."""
    lines = [
        "# Autogenerated by linacre.py",
        "# Do not commit this file to git\n",
    ]
    for k, v in env_vars.items():
        lines.append(f"{k}={v}")
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _run(cmd_args: list[str], input_data: str | None = None, timeout: int | None = None, cwd: str | None = None):
    """Run a subprocess and return (ok, stdout, stderr)."""
    try:
        stdin_val = None if input_data is not None else subprocess.DEVNULL
        res = subprocess.run(
            cmd_args,
            text=True,
            input=input_data,
            stdin=stdin_val,
            capture_output=True,
            timeout=timeout,
            cwd=cwd,
        )
        return res.returncode == 0, res.stdout.strip(), res.stderr.strip()
    except subprocess.TimeoutExpired:
        return False, "", "Command timed out"
    except Exception as e:
        return False, "", str(e)


def _is_vercel_logged_in() -> bool:
    """Check Vercel CLI auth config files."""
    paths = [
        Path(os.environ.get("LOCALAPPDATA", "")) / "com.vercel.cli" / "auth.json",
        Path(os.environ.get("APPDATA", "")) / "com.vercel.cli" / "auth.json",
        Path(os.environ.get("APPDATA", "")) / "xdg.data" / "com.vercel.cli" / "auth.json",
        Path.home() / ".config" / "vercel" / "auth.json",
    ]
    for p in paths:
        if p.exists():
            try:
                data = json.loads(p.read_text(encoding="utf-8"))
                if data.get("token"):
                    return True
            except Exception:
                pass
    return False


def _node_version() -> str | None:
    """Get installed Node.js version."""
    ok, out, _ = _run(["node", "--version"], timeout=5)
    return out if ok else None


def _npm_bin() -> str:
    """Return the npm command name (npm.cmd on Windows)."""
    return "npm.cmd" if sys.platform == "win32" else "npm"


# ─── Commands ────────────────────────────────────────────────────────────────

def cmd_setup():
    """Scan Windows Registry for developer API keys and sync to .env."""
    _banner("Environment Setup")
    _info("Scanning Windows Registry for developer API keys...")

    env_vars = _read_env()
    updated = False

    for key in KEYS_TO_SYNC:
        val = _get_windows_env(key)
        if val:
            if env_vars.get(key) != val:
                env_vars[key] = val
                _ok(f"Synchronized: {key}")
                updated = True
            else:
                _ok(f"Up to date: {key}")
        else:
            _warn(f"Not found in Windows environment: {key}")

    # Ensure PORT is set
    if "PORT" not in env_vars:
        env_vars["PORT"] = "3000"

    _write_env(env_vars)

    if updated:
        _ok(f"Workspace .env written → {ENV_PATH}")
    else:
        _info("No changes needed — .env is already current.")


def cmd_sync():
    """Push local .env secrets to Vercel environment."""
    _banner("Vercel Secret Sync")

    vercel_bin = "vercel.cmd" if sys.platform == "win32" else "vercel"

    if not _is_vercel_logged_in():
        _warn("Vercel CLI is not logged in.")
        _info("Run: vercel login")
        return

    ok, stdout, stderr = _run([vercel_bin, "whoami"], timeout=5, cwd=str(PROJECT_DIR))
    if not ok:
        _warn(f"Vercel session validation failed: {stderr}")
        _info("Run: vercel login")
        return
    _ok(f"Logged in as: {stdout}")

    if not ENV_PATH.exists():
        _warn("No .env file found. Run: python linacre.py setup")
        return

    env_vars = _read_env()
    secrets = {k: v for k, v in env_vars.items() if k in KEYS_TO_SYNC and v}

    if not secrets:
        _info("No developer API keys found in .env to sync.")
        return

    _info(f"Found {len(secrets)} secrets to push to Vercel.")

    for k, v in secrets.items():
        _info(f"Syncing {k}...")
        for env_name in ("production", "preview", "development"):
            res = subprocess.run(
                [vercel_bin, "env", "add", k, env_name, "--value", v, "--yes"],
                capture_output=True, text=True,
                cwd=str(PROJECT_DIR),
            )
            out = (res.stderr or res.stdout or "").strip()
            if res.returncode == 0:
                _ok(f"  {env_name} ✓")
            elif "already been added" in out:
                _ok(f"  {env_name} ✓ (already exists)")
            else:
                _warn(f"  {env_name} ✗: {out[:60]}")

    _ok("Vercel environment sync complete!")


def cmd_dev():
    """Install deps if needed, sync env, start dev server."""
    _banner("Dev Server")

    # Auto-install if node_modules is missing
    nm = PROJECT_DIR / "node_modules"
    if not nm.exists():
        _info("Installing npm dependencies (first run)...")
        subprocess.run([_npm_bin(), "install"], cwd=str(PROJECT_DIR))
        print()

    # Sync env
    cmd_setup()
    print()

    # Start dev server (tsx api/server.ts)
    _info("Starting dev server...")
    try:
        tsx_bin = "tsx.cmd" if sys.platform == "win32" else "tsx"
        # Try local tsx first
        local_tsx = PROJECT_DIR / "node_modules" / ".bin" / ("tsx.cmd" if sys.platform == "win32" else "tsx")
        if local_tsx.exists():
            tsx_bin = str(local_tsx)

        subprocess.run(
            [tsx_bin, "api/server.ts"],
            cwd=str(PROJECT_DIR),
        )
    except KeyboardInterrupt:
        print(f"\n{DIM}  Server stopped.{RESET}")


def cmd_build():
    """Sync env and run production build."""
    _banner("Production Build")
    cmd_setup()
    print()
    _info("Running Vite build + esbuild server bundle...")
    subprocess.run([_npm_bin(), "run", "build"], cwd=str(PROJECT_DIR))


def cmd_open():
    """Open linacre.site in default browser."""
    _info("Opening linacre.site...")
    webbrowser.open("https://linacre.site")


def cmd_status():
    """Show project health status."""
    _banner("Project Health")

    # Node version
    nv = _node_version()
    if nv:
        _ok(f"Node.js: {nv}")
    else:
        _warn("Node.js: not found in PATH")

    # npm version
    ok, out, _ = _run([_npm_bin(), "--version"], timeout=5)
    if ok:
        _ok(f"npm: v{out}")
    else:
        _warn("npm: not found")

    # .env status
    if ENV_PATH.exists():
        env_vars = _read_env()
        found_keys = [k for k in KEYS_TO_SYNC if k in env_vars and env_vars[k]]
        _ok(f".env: {len(found_keys)}/{len(KEYS_TO_SYNC)} API keys configured")
        for k in KEYS_TO_SYNC:
            if k in env_vars and env_vars[k]:
                masked = env_vars[k][:8] + "..." if len(env_vars[k]) > 8 else "***"
                _ok(f"  {k} = {masked}")
            else:
                _warn(f"  {k} = (missing)")
    else:
        _warn(".env: not found — run: python linacre.py setup")

    # Vercel
    if _is_vercel_logged_in():
        _ok("Vercel CLI: authenticated")
    else:
        _warn("Vercel CLI: not logged in")

    # node_modules
    nm = PROJECT_DIR / "node_modules"
    if nm.exists():
        _ok("node_modules: installed")
    else:
        _warn("node_modules: missing — run: npm install")

    # Git
    ok, out, _ = _run(["git", "rev-parse", "--short", "HEAD"], timeout=5, cwd=str(PROJECT_DIR))
    if ok:
        _ok(f"Git HEAD: {out}")
    else:
        _warn("Git: not a repository or git not found")

    print()


def cmd_boot():
    """Zero-click auto-startup for Windows."""
    _banner("Zero-Click PC Boot Sequence")
    
    # 1. Start Dev Server
    _info("Starting dev server in background...")
    tsx_bin = "tsx.cmd" if sys.platform == "win32" else "tsx"
    local_tsx = PROJECT_DIR / "node_modules" / ".bin" / ("tsx.cmd" if sys.platform == "win32" else "tsx")
    if local_tsx.exists():
        tsx_bin = str(local_tsx)
        
    subprocess.Popen(
        [tsx_bin, "api/server.ts"],
        cwd=str(PROJECT_DIR),
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        creationflags=subprocess.CREATE_NEW_PROCESS_GROUP if sys.platform == "win32" else 0,
        shell=sys.platform == "win32"
    )
    
    _info("Waiting for port 3000 to be ready...")
    time.sleep(4)
    
    # 2. Open Browser
    cmd_open()
    
    # 3. Spawn AI Agent
    agent_script = PROJECT_DIR / "scripts" / "autonomous_agent.ts"
    if agent_script.exists():
        _info("Spawning background AI Agent monitor...")
        subprocess.Popen(
            [tsx_bin, str(agent_script)],
            cwd=str(PROJECT_DIR),
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            creationflags=subprocess.CREATE_NEW_PROCESS_GROUP if sys.platform == "win32" else 0,
            shell=sys.platform == "win32"
        )
    else:
        _warn("Agent script not found, skipping.")
        
    # 3b. Pixel-Agents Office Server (Removed)
    pass
        
    # 4. Spawn Background Git Auto-Sync
    sync_script = Path("D:/LIN4CRE/linacre-toolkit/git-sync.ps1")
    if sync_script.exists():
        _info("Spawning background Git Auto-Sync loop (every 1 hour)...")
        ps_cmd = f"& {{ & '{sync_script}'; while($true) {{ Start-Sleep -Seconds 3600; & '{sync_script}' }} }}"
        subprocess.Popen(
            ["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-WindowStyle", "Hidden", "-Command", ps_cmd],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            creationflags=subprocess.CREATE_NEW_PROCESS_GROUP if sys.platform == "win32" else 0,
            shell=sys.platform == "win32"
        )
    else:
        _warn("Git sync script not found, skipping.")

    # 5. Spawn Background Vault Watcher
    watcher_script = Path("D:/LIN4CRE/linacre-toolkit/vault-watcher.ps1")
    if watcher_script.exists():
        _info("Spawning background Vault Watcher...")
        subprocess.Popen(
            ["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-WindowStyle", "Hidden", "-File", str(watcher_script)],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            creationflags=subprocess.CREATE_NEW_PROCESS_GROUP if sys.platform == "win32" else 0,
            shell=sys.platform == "win32"
        )
    else:
        _warn("Vault watcher script not found, skipping.")
        
    _ok("Boot sequence complete! System is fully autonomous.")


def cmd_verify():
    """Verify all secrets match across Registry, .env, and Vercel."""
    _banner("Secrets Verification")
    errors = 0

    env_vars = _read_env()
    _info(f"Reading {len(KEYS_TO_SYNC)} tracked keys...\n")

    for key in KEYS_TO_SYNC:
        reg = _get_windows_env(key)
        env = env_vars.get(key)
        line = f"  {key:40s}"

        if not reg and not env:
            _warn(f"{line}  MISSING in Registry and .env")
            errors += 1
        elif reg and not env:
            _warn(f"{line}  Registry ✓  .env MISSING")
            errors += 1
        elif env and not reg:
            _warn(f"{line}  Registry MISSING  .env ✓")
            errors += 1
        elif reg != env:
            _warn(f"{line}  MISMATCH (Registry vs .env)")
            errors += 1
        else:
            masked = reg[:10] + "..." if len(reg) > 10 else reg
            _ok(f"{line}  Registry=.env ({masked})")

    print()
    if errors == 0:
        _ok("All secrets match across Registry and .env.")
    else:
        _warn(f"{errors} discrepancy/ies found. Run: python linacre.py setup")

    vercel_bin = "vercel.cmd" if sys.platform == "win32" else "vercel"
    ok, out, _ = _run([vercel_bin, "whoami"], timeout=8, cwd=str(PROJECT_DIR))
    if ok:
        _ok(f"Vercel logged in as: {out}")
        _info("Run 'python linacre.py sync' to push any .env changes to Vercel.")
    else:
        _warn("Vercel CLI not logged in. Secrets may be stale on Vercel.")


def cmd_audit():
    """Scan for hardcoded secrets in config files."""
    _banner("Secrets Audit")
    patterns = [
        "sk-proj-", "sk-ant-", "sk-or-v1-", "ghp_", "gho_",
        "AIzaSy", "hf_", "xox[bp]-",
    ]
    scan_dirs = [
        PROJECT_DIR,
        Path.home() / ".openclaw",
    ]
    skip_patterns = [".env", "node_modules", ".git", "dist", "__pycache__"]
    findings = 0

    for scan_dir in scan_dirs:
        if not scan_dir.exists():
            continue
        for f in scan_dir.rglob("*"):
            if any(s in str(f) for s in skip_patterns):
                continue
            if not f.is_file():
                continue
            try:
                text = f.read_text(encoding="utf-8", errors="replace")
            except Exception:
                continue
            for i, line in enumerate(text.splitlines(), 1):
                stripped = line.strip()
                if stripped.startswith("#") or stripped.startswith("//"):
                    continue
                for pat in patterns:
                    if pat in stripped and len(stripped) < 200:
                        _warn(f"  {f}:{i} matches '{pat}'")
                        findings += 1
                        break

    if findings == 0:
        _ok("No hardcoded secrets detected.")
    else:
        _warn(f"{findings} potential hardcoded secret(s) found. Review and migrate to Registry + .env.")

    _info(f"\nSecret policy: Registry is the single source of truth.")
    _info(f".env is synced from Registry via: python linacre.py setup")
    _info(f"Vercel is synced from .env via: python linacre.py sync")
    _info(f"Config files should use ${{VAR_NAME}} references, never plaintext values.")


def cmd_help():
    """Show help message."""
    print(__doc__)


# ─── Main ────────────────────────────────────────────────────────────────────

COMMANDS = {
    "setup": cmd_setup,
    "sync": cmd_sync,
    "dev": cmd_dev,
    "build": cmd_build,
    "open": cmd_open,
    "status": cmd_status,
    "verify": cmd_verify,
    "audit": cmd_audit,
    "boot": cmd_boot,
    "help": cmd_help,
}


def main():
    _set_encoding()

    if len(sys.argv) < 2 or sys.argv[1] not in COMMANDS:
        cmd_help()
        if len(sys.argv) >= 2 and sys.argv[1] not in COMMANDS:
            _warn(f"Unknown command: {sys.argv[1]}")
            print(f"\n  Available: {', '.join(COMMANDS.keys())}")
        sys.exit(0)

    COMMANDS[sys.argv[1]]()


if __name__ == "__main__":
    main()
