# setup_env.py
# Script to read API keys directly from Windows User/System Registry
# and synchronize them to the local workspace .env file.

import os
import sys

# Windows Registry module
if sys.platform == 'win32':
    import winreg
else:
    winreg = None

def get_windows_env(name):
    if not winreg:
        return os.environ.get(name)
    
    # 1. Try HKEY_CURRENT_USER\Environment
    try:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, 'Environment') as key:
            value, _ = winreg.QueryValueEx(key, name)
            return value
    except FileNotFoundError:
        pass
        
    # 2. Try HKEY_LOCAL_MACHINE Registry
    try:
        with winreg.OpenKey(
            winreg.HKEY_LOCAL_MACHINE, 
            r'SYSTEM\CurrentControlSet\Control\Session Manager\Environment'
        ) as key:
            value, _ = winreg.QueryValueEx(key, name)
            return value
    except FileNotFoundError:
        pass
        
    # 3. Fallback to process env
    return os.environ.get(name)

def main():
    # Set encoding to utf-8 if possible
    if hasattr(sys.stdout, 'reconfigure'):
        try:
            sys.stdout.reconfigure(encoding='utf-8')
        except Exception:
            pass

    print("[INFO] Scanning Windows Registry for developer API keys...")
    
    keys = ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY", "CLAUDE_API_KEY", "LITELLM_API_KEY"]
    env_vars = {}
    
    # Load existing .env
    env_path = os.path.join(os.path.dirname(__file__), ".env")
    if os.path.exists(env_path):
        print("[INFO] Reading existing .env file...")
        with open(env_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    env_vars[k.strip()] = v.strip()
                    
    # Scan and sync
    updated = False
    for k in keys:
        val = get_windows_env(k)
        if val:
            existing = env_vars.get(k)
            if existing != val:
                env_vars[k] = val
                print(f"[SUCCESS] Found and synchronized: {k}")
                updated = True
            else:
                print(f"[OK] Up to date: {k}")
        else:
            print(f"[WARN] Not found in Windows environment: {k}")
            
    # Set default port
    if "PORT" not in env_vars:
        env_vars["PORT"] = "3000"
        
    # Save back to .env
    with open(env_path, "w", encoding="utf-8") as f:
        f.write("# Autogenerated by setup_env.py\n")
        f.write("# Do not commit this file to git repository\n\n")
        for k, v in env_vars.items():
            f.write(f"{k}={v}\n")
            
    print("\n[SUCCESS] Workspace .env synchronized successfully!")
    print(f"Location: {env_path}")
    print("Run 'npm run dev' to start your local dev server.")

if __name__ == "__main__":
    main()
